# Generated by Django 3.1.3 on 2020-11-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=10, max_length=1000),
            preserve_default=False,
        ),
    ]
